const bodyParts = {
  DEFENDER: [TOUGH, TOUGH, TOUGH, TOUGH, TOUGH, TOUGH, TOUGH, ATTACK, MOVE, MOVE, MOVE], // 300
  FIGHTER: [ATTACK, ATTACK, MOVE, MOVE], // 260
  HEALER: [HEAL, MOVE], // 300
  SCOUT: [ATTACK, MOVE, MOVE, MOVE, MOVE], // 280
  WORKER: [CARRY, WORK, MOVE], // 200
};

module.exports = bodyParts;
